(use gauche.test)

(require "./faTL")

(test-start "faTL")

(test-section "faTL->uc: single character")
(test* "alef" "ا" (faTL->uc "@")) ;A
(test* "be" "ب" (faTL->uc "B"))
(test* "pe" "پ" (faTL->uc "P"))
(test* "te" "ت" (faTL->uc "T"))
(test* "se" "ث" (faTL->uc "Th"))
(test* "ji:m" "ج" (faTL->uc "J"))
(test* "che" "چ" (faTL->uc "Ch"))
(test* "he" "ح" (faTL->uc ".H"))
(test* "khe" "خ" (faTL->uc "Kh"))
(test* "da:l" "د" (faTL->uc "D"))
(test* "za:l" "ذ" (faTL->uc "Dz"))
(test* "re" "ر" (faTL->uc "R"))
(test* "ze" "ز" (faTL->uc "Rz"))
(test* "zhe" "ژ" (faTL->uc "Rzh"))
(test* "si:n" "س" (faTL->uc "S"))
(test* "shi:n" "ش" (faTL->uc "Sh"))
(test* "sa:d" "ص" (faTL->uc ".S"))
(test* "za:d" "ض" (faTL->uc ".Sz"))
(test* "ta:" "ط" (faTL->uc ".T"))
(test* "za:" "ظ" (faTL->uc ".Tz"))
(test* "ein" "ع" (faTL->uc "`"))
(test* "ghein" "غ" (faTL->uc "Gh"))
(test* "fe" "ف" (faTL->uc "F"))
(test* "qa:f" "ق" (faTL->uc "Q"))
(test* "ka:f" "ک" (faTL->uc "K"))
(test* "ga:f" "گ" (faTL->uc "G"))
(test* "la:m" "ل" (faTL->uc "L"))
(test* "mi:n" "م" (faTL->uc "M"))
(test* "nu:n" "ن" (faTL->uc "N"))
(test* "vav" "و" (faTL->uc "V"))
(test* "he" "ه" (faTL->uc "H"))
(test* "ye" "ی" (faTL->uc "Y"))

(test* "alef + madda" "آ" (faTL->uc "A")) ; A~
(test* "alef ye" "اي" (faTL->uc "I"))
(test* "alef vav" "او" (faTL->uc "U"))
(test* "?" "؟" (faTL->uc "?"))

(test-section "faTL->uc: some words")
(test* "AN" "آن" (faTL->uc "AN"))
(test* "KTAB" "کتاب" (faTL->uc "KTAB"))
(test* "@ST" "است" (faTL->uc "@ST"))
(test* "IN" "اين" (faTL->uc "IN"))
(test* "BRzRG" "بزرگ" (faTL->uc "BRzRG"))
(test* "SG" "سگ" (faTL->uc "SG"))
(test* "KVChK" "کوچک" (faTL->uc "KVChK"))
;(test* "KUChK" "کوچک" (faTL->uc "KUChK"))
(test* "MDAD" "مداد" (faTL->uc "MDAD"))
(test* "@SB" "اسب" (faTL->uc "@SB"))
(test* "DRKhT" "درخت" (faTL->uc "DRKhT"))
(test* "KAGhDz" "کاغذ" (faTL->uc "KAGhDz"))
(test* "NAN" "نان" (faTL->uc "NAN"))
(test* "AB" "آب" (faTL->uc "AB"))
(test* "SRD" "سرد" (faTL->uc "SRD"))
(test* "GL" "گل" (faTL->uc "GL"))
(test* "QShNG" "قشنگ" (faTL->uc "QShNG"))
(test* "SYB" "سیب" (faTL->uc "SYB"))
;(test* "SIB" "سیب" (faTL->uc "SIB"))
(test* "GRBH" "گربه" (faTL->uc "GRBH"))
(test* "SFYD" "سفید" (faTL->uc "SFYD"))
(test* "AYA" "آیا" (faTL->uc "AYA"))
(test* "BLH" "بله" (faTL->uc "BLH"))
(test* "NH KhYR" "نه خیر" (faTL->uc "NH KhYR"))
(test* "NKhYR" "نخیر" (faTL->uc "NKhYR"))
(test* "NYST" "نیست" (faTL->uc "NYST"))
(test* "ChYST" "چیست" (faTL->uc "ChYST"))
(test* "ChH" "چه" (faTL->uc "ChH"))
(test* "KY" "کی" (faTL->uc "KY"))
(test* "KYST" "کیست" (faTL->uc "KYST"))
(test* "KJA" "کجا" (faTL->uc "KJA"))
(test* "KJAST" "کجاست" (faTL->uc "KJAST"))
(test* "INJA" "اينجا" (faTL->uc "INJA"))

(test* "AN KTAB @ST" "آن کتاب است" (faTL->uc "AN KTAB @ST"))
(test* "IN KTAB @ST" "اين کتاب است" (faTL->uc "IN KTAB @ST"))
(test* "IN KTAB BRzRG @ST" "اين کتاب بزرگ است" (faTL->uc "IN KTAB BRzRG @ST"))
(test* "AN SG KVChK @ST" "آن سگ کوچک است" (faTL->uc "AN SG KVChK @ST"))
;(test* "AN SG KUChK @ST" "آن سگ کوچک است" (faTL->uc "AN SG KUChK @ST"))
;(test-end)

;;
;(test-start "uc->faTL")
(test-section "uc->faTL: single character")
(test* "ا" "@" (uc->faTL "ا"))
(test* "ب" "B" (uc->faTL "ب"))
(test* "پ" "P" (uc->faTL "پ"))
(test* "ت" "T" (uc->faTL "ت"))
(test* "ث" "Th" (uc->faTL "ث"))
(test* "ج" "J" (uc->faTL "ج"))
(test* "چ" "Ch" (uc->faTL "چ"))
(test* "ح" ".H" (uc->faTL "ح"))
(test* "خ" "Kh" (uc->faTL "خ"))
(test* "د" "D" (uc->faTL "د"))
(test* "ذ" "Dz" (uc->faTL "ذ"))
(test* "ر" "R" (uc->faTL "ر"))
(test* "ز" "Rz" (uc->faTL "ز"))
(test* "ژ" "Rzh" (uc->faTL "ژ"))
(test* "س" "S" (uc->faTL "س"))
(test* "ش" "Sh" (uc->faTL "ش"))
(test* "ص" ".S" (uc->faTL "ص"))
(test* "ض" ".Sz" (uc->faTL "ض"))
(test* "ط" ".T" (uc->faTL "ط"))
(test* "ظ" ".Tz" (uc->faTL "ظ"))
(test* "ع" "`" (uc->faTL "ع"))
(test* "غ" "Gh" (uc->faTL "غ"))
(test* "ف" "F" (uc->faTL "ف"))
(test* "ق" "Q" (uc->faTL "ق"))
(test* "ک" "K" (uc->faTL "ک"))
(test* "گ" "G" (uc->faTL "گ"))
(test* "ل" "L" (uc->faTL "ل"))
(test* "م" "M" (uc->faTL "م"))
(test* "ن" "N" (uc->faTL "ن"))
(test* "و" "V" (uc->faTL "و"))
(test* "ه" "H" (uc->faTL "ه"))
(test* "ی" "Y" (uc->faTL "ی"))

(test* "آ" "A" (uc->faTL "آ")) ; alef + madda
(test* "اي" "I" (uc->faTL "اي")) ; alef ye
(test* "او" "U" (uc->faTL "او")) ; alef vav
(test* "؟" "?" (uc->faTL "؟")) ;?

(test-section "uc->faTL: some words")
(test* "آن" "AN" (uc->faTL "آن"))
(test* "کتاب" "KTAB" (uc->faTL "کتاب"))
(test* "است" "@ST" (uc->faTL "است"))

(test* "آن کتاب است" "AN KTAB @ST" (uc->faTL "آن کتاب است"))
(test* "اين کتاب است" "IN KTAB @ST" (uc->faTL "اين کتاب است"))
(test* "اين کتاب بزرگ است" "IN KTAB BRzRG @ST" (uc->faTL "اين کتاب بزرگ است"))
(test* "آن سگ کوچک است" "AN SG KUChK @ST" (uc->faTL "آن سگ کوچک است"))

(test-end)
