(use gauche.test)

(test-start "faTL")
(require "./faTL")
;;
;; faTL->uc
;;
(test-section "faTL->uc: single character")
(test* "alef" "ا" (faTL->uc "@"))
(test* "be" "ب" (faTL->uc "B"))
(test* "pe" "پ" (faTL->uc "P"))
(test* "te" "ت" (faTL->uc "T"))
(test* "se" "ث" (faTL->uc "Th"))
(test* "ji:m" "ج" (faTL->uc "J"))
(test* "che" "چ" (faTL->uc "Ch"))
(test* "he" "ح" (faTL->uc ".H"))
(test* "khe" "خ" (faTL->uc "Kh"))
(test* "da:l" "د" (faTL->uc "D"))
(test* "za:l" "ذ" (faTL->uc "Dz"))
(test* "re" "ر" (faTL->uc "R"))
(test* "ze" "ز" (faTL->uc "Rz"))
(test* "zhe" "ژ" (faTL->uc "Rzh"))
(test* "si:n" "س" (faTL->uc "S"))
(test* "shi:n" "ش" (faTL->uc "Sh"))
(test* "sa:d" "ص" (faTL->uc ".S"))
(test* "za:d" "ض" (faTL->uc ".Sz"))
(test* "ta:" "ط" (faTL->uc ".T"))
(test* "za:" "ظ" (faTL->uc ".Tz"))
(test* "ein" "ع" (faTL->uc "`"))
(test* "ghein" "غ" (faTL->uc "Gh"))
(test* "fe" "ف" (faTL->uc "F"))
(test* "qa:f" "ق" (faTL->uc "Q"))
(test* "ka:f" "ک" (faTL->uc "K"))
(test* "ga:f" "گ" (faTL->uc "G"))
(test* "la:m" "ل" (faTL->uc "L"))
(test* "mi:n" "م" (faTL->uc "M"))
(test* "nu:n" "ن" (faTL->uc "N"))
(test* "vav" "و" (faTL->uc "V"))
(test* "he" "ه" (faTL->uc "H"))
(test* "ye" "ی" (faTL->uc "Y"))

(test* "alef + madda" "آ" (faTL->uc "A")) ; A~
(test* "alef ye" "ای" (faTL->uc "I"))
(test* "alef vav" "او" (faTL->uc "U"))
(test* "?" "؟" (faTL->uc "?"))

;;
;; uc->faTL
;;
(test-section "uc->faTL: single character")
(test* "alef" "@" (uc->faTL "ا"))
(test* "be" "B" (uc->faTL "ب"))
(test* "pe" "P" (uc->faTL "پ"))
(test* "te" "T" (uc->faTL "ت"))
(test* "se" "Th" (uc->faTL "ث"))
(test* "ji:m" "J" (uc->faTL "ج"))
(test* "che" "Ch" (uc->faTL "چ"))
(test* "he" ".H" (uc->faTL "ح"))
(test* "khe" "Kh" (uc->faTL "خ"))
(test* "da:l" "D" (uc->faTL "د"))
(test* "za:l" "Dz" (uc->faTL "ذ"))
(test* "re" "R" (uc->faTL "ر"))
(test* "ze" "Rz" (uc->faTL "ز"))
(test* "zhe" "Rzh" (uc->faTL "ژ"))
(test* "si:n" "S" (uc->faTL "س"))
(test* "shi:n" "Sh" (uc->faTL "ش"))
(test* "sa:d" ".S" (uc->faTL "ص"))
(test* "za:d" ".Sz" (uc->faTL "ض"))
(test* "ta:" ".T" (uc->faTL "ط"))
(test* "za:" ".Tz" (uc->faTL "ظ"))
(test* "ein" "`" (uc->faTL "ع"))
(test* "ghein" "Gh" (uc->faTL "غ"))
(test* "fe" "F" (uc->faTL "ف"))
(test* "qa:f" "Q" (uc->faTL "ق"))
(test* "ka:f" "K" (uc->faTL "ک"))
(test* "ga:f" "G" (uc->faTL "گ"))
(test* "la:m" "L" (uc->faTL "ل"))
(test* "mi:n" "M" (uc->faTL "م"))
(test* "nu:n" "N" (uc->faTL "ن"))
(test* "vav" "V" (uc->faTL "و"))
(test* "he" "H" (uc->faTL "ه"))
(test* "ye" "Y" (uc->faTL "ی"))

(test* "alef + madda" "A" (uc->faTL "آ"))
(test* "alef ye" "I" (uc->faTL "ای"))
(test* "alef vav" "U" (uc->faTL "او"))
(test* "?" "?" (uc->faTL "؟"))

;;
;; 相互変換テスト
;;
(define (same-length-space-of s) (make-string (string-length s)))

(test-section "faTL->uc / uc->faTL: mutual convert test")
(define-macro (mutual-convert-test faTL uc)
  `(begin
	 (test* ,(string-append faTL " : faTL->uc") ,uc (faTL->uc ,faTL))
	 (test* ,(string-append (same-length-space-of faTL) " : uc->faTL") ,faTL (uc->faTL ,uc)) ))

(mutual-convert-test "AN" "آن")
(mutual-convert-test "KTAB" "کتاب")
(mutual-convert-test "@ST" "است")
(mutual-convert-test "IN" "این")
(mutual-convert-test "BRzRG" "بزرگ")
(mutual-convert-test "SG" "سگ")
(mutual-convert-test "KUChK" "کوچک")
(mutual-convert-test "MDAD" "مداد")
(mutual-convert-test "@SB" "اسب")
(mutual-convert-test "DRKhT" "درخت")
(mutual-convert-test "KAGhDz" "کاغذ")
(mutual-convert-test "NAN" "نان")
(mutual-convert-test "AB" "آب")
(mutual-convert-test "SRD" "سرد")
(mutual-convert-test "GL" "گل")
(mutual-convert-test "QShNG" "قشنگ")
(mutual-convert-test "SIB" "سیب")
(mutual-convert-test "GRBH" "گربه")
(mutual-convert-test "SFID" "سفید")
(mutual-convert-test "AYA" "آیا")
(mutual-convert-test "BLH" "بله")
(mutual-convert-test "NH KhIR" "نه خیر")
(mutual-convert-test "NKhIR" "نخیر")
(mutual-convert-test "NIST" "نیست")
(mutual-convert-test "ChIST" "چیست")
(mutual-convert-test "ChH" "چه")
(mutual-convert-test "KI" "کی")
(mutual-convert-test "KIST" "کیست")
(mutual-convert-test "KJA" "کجا")
(mutual-convert-test "KJAST" "کجاست")
(mutual-convert-test "INJA" "اینجا")

(mutual-convert-test "AN KTAB @ST" "آن کتاب است")
(mutual-convert-test "IN KTAB @ST" "این کتاب است")
(mutual-convert-test "IN KTAB BRzRG @ST" "این کتاب بزرگ است")
(mutual-convert-test "AN SG KUChK @ST" "آن سگ کوچک است")

(test-end)
